config/routes.rb
Rails.application.routes.draw do
  resources :u_suitcases

  resources :sessions

  resources :item_types

  resources :users

  resources :items

  resources :countries

  get 'home/index'
  root 'home#index'

  post 'suitcases' => 'suitcases#find_suitcase'
  post 'u_suitcases/get_u_suitcases' => 'u_suitcases#get_user_suitcases'

end

app/models/country.rb
class Country < ActiveRecord::Base
	has_many :user
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy, :travel]

  skip_before_action :verify_authenticity_token, only: [:travel,:create]


  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
    render json: {countries: @countries}
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /countries/1/travel.json
  def travel
    # On crée un nouvel objet travel à partir des paramètres reçus
    @travel = Travel.new(travel_params)
    # On précise que cet object Travel dépend du country concerné
    #@travel.country = @country

    respond_to do |format|
      if @travel.save
        format.json
      else
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:name, :flag, :weatherLink)
    end

        # On ajoute les paramètres qu'on va envoyer avec le booking
    def travel_params
      params.require(:travel).permit(:user_id, :country_id)
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/country/_form.html.erb
<%= form_for @country, :html => { :class => "form-horizontal country" } do |f| %>

    <% if @country.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@country.errors.count, "error") %> prohibited this country from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @country.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@country[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :flag, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :flag, :class => 'form-control' %>
    </div>
    <%= error_span(@country[:flag]) %>
  </div>
  <div class="control-group">
    <%= f.label :weatherLink, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :weatherLink, :class => 'form-control' %>
    </div>
    <%= error_span(@country[:weatherLink]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            countries_path, :class => 'btn btn-default' %>

<% end %>

app/views/country/edit.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/country/index.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:flag) %></th>
      <th><%= model_class.human_attribute_name(:weatherLink) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= link_to country.id, country_path(country) %></td>
        <td><%= country.name %></td>
        <td><%= country.flag %></td>
        <td><%= country.weatherLink %></td>
        <td><%=l country.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_country_path(country), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      country_path(country),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_country_path,
            :class => 'btn btn-primary' %>

app/views/country/new.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/country/show.html.erb
<%- model_class = Country -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @country.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:flag) %>:</strong></dt>
  <dd><%= @country.flag %></dd>
  <dt><strong><%= model_class.human_attribute_name(:weatherLink) %>:</strong></dt>
  <dd><%= @country.weatherLink %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              countries_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_country_path(@country), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              country_path(@country),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>