config/routes.rb
Rails.application.routes.draw do
  resources :u_suitcases

  resources :sessions

  resources :item_types

  resources :users

  resources :items

  resources :countries

  get 'home/index'
  root 'home#index'

  post 'suitcases' => 'suitcases#find_suitcase'
  post 'u_suitcases/get_u_suitcases' => 'u_suitcases#get_user_suitcases'

end

app/controllers/u_suitcases_controller.rb
class USuitcasesController < ApplicationController
  before_action :set_u_suitcase, only: [:show, :edit, :update, :destroy]
    skip_before_action :verify_authenticity_token

  # GET /u_suitcases
  # GET /u_suitcases.json
  def index
    @u_suitcases = USuitcase.all
  end

  # GET /u_suitcases/1
  # GET /u_suitcases/1.json
  def show
  end

  # GET /u_suitcases/new
  def new
    @u_suitcase = USuitcase.new
  end

  # GET /u_suitcases/1/edit
  def edit
  end

  # POST /u_suitcases
  # POST /u_suitcases.json
  def create
    @u_suitcase = USuitcase.new(u_suitcase_params)

    respond_to do |format|
      if @u_suitcase.save
        format.html { redirect_to @u_suitcase, notice: 'U suitcase was successfully created.' }
        format.json { render :show, status: :created, location: @u_suitcase }
      else
        format.html { render :new }
        format.json { render json: @u_suitcase.errors, status: :unprocessable_entity }
      end
    end
  end

  def get_user_suitcases
    u_suitcases = USuitcase.where(user_id: u_suitcase_params[:user_id])

    respond_to do |format|
      format.json  {render json: {:suitcases => u_suitcases}}
    end
  end


  # PATCH/PUT /u_suitcases/1
  # PATCH/PUT /u_suitcases/1.json
  def update
    respond_to do |format|
      if @u_suitcase.update(u_suitcase_params)
        format.html { redirect_to @u_suitcase, notice: 'U suitcase was successfully updated.' }
        format.json { render :show, status: :ok, location: @u_suitcase }
      else
        format.html { render :edit }
        format.json { render json: @u_suitcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /u_suitcases/1
  # DELETE /u_suitcases/1.json
  def destroy
    @u_suitcase.destroy
    respond_to do |format|
      format.html { redirect_to u_suitcases_url, notice: 'U suitcase was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_u_suitcase
      @u_suitcase = USuitcase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def u_suitcase_params
      params.require(:u_suitcase).permit(:user_id, :country_id, :weather)
    end
end

app/helpers/u_suitcases_helper.rb
module USuitcasesHelper
end

app/views/u_suitcases/_form.html.erb
<%= form_for(@u_suitcase) do |f| %>
  <% if @u_suitcase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@u_suitcase.errors.count, "error") %> prohibited this u_suitcase from being saved:</h2>

      <ul>
      <% @u_suitcase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :country_id %><br>
    <%= f.text_field :country_id %>
  </div>
  <div class="field">
    <%= f.label :weather %><br>
    <%= f.text_field :weather %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/u_suitcases/edit.html.erb
<h1>Editing u_suitcase</h1>

<%= render 'form' %>

<%= link_to 'Show', @u_suitcase %> |
<%= link_to 'Back', u_suitcases_path %>

app/views/u_suitcases/index.html.erb
<h1>Listing u_suitcases</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Country</th>
      <th>Weather</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @u_suitcases.each do |u_suitcase| %>
      <tr>
        <td><%= u_suitcase.user %></td>
        <td><%= u_suitcase.country %></td>
        <td><%= u_suitcase.weather %></td>
        <td><%= link_to 'Show', u_suitcase %></td>
        <td><%= link_to 'Edit', edit_u_suitcase_path(u_suitcase) %></td>
        <td><%= link_to 'Destroy', u_suitcase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New U suitcase', new_u_suitcase_path %>

app/views/u_suitcases/new.html.erb
<h1>New u_suitcase</h1>

<%= render 'form' %>

<%= link_to 'Back', u_suitcases_path %>

app/views/u_suitcases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @u_suitcase.user %>
</p>

<p>
  <strong>Country:</strong>
  <%= @u_suitcase.country %>
</p>

<p>
  <strong>Weather:</strong>
  <%= @u_suitcase.weather %>
</p>

<%= link_to 'Edit', edit_u_suitcase_path(@u_suitcase) %> |
<%= link_to 'Back', u_suitcases_path %>